#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd $SCRIPT_DIR

PROJECTS="ffmpeg libarchive openjpeg proj4 wireshark"

# The main procedure

rm -f Makefile

echo "# This Makefile is automatically generated by rebuild_makefile.sh." >> Makefile
echo "# Consider re-running the script instead of editing this file." >> Makefile
echo >> Makefile
echo "all: $PROJECTS" >> Makefile
echo >> Makefile

for PROJECT_NAME in $PROJECTS
do
    echo -n "$PROJECT_NAME: " >> Makefile
    
    for BUG_NUMBER in `ls -d "projects/$PROJECT_NAME"_* | sed s/[^[:digit:]]/\ /g`
    do
	if [ x$BUG_NUMBER != x4 ] ; then
	    echo -n "$PROJECT_NAME"_"$BUG_NUMBER".log " " >> Makefile
	fi
    done
    echo >> Makefile
    echo >> Makefile
    
    for BUG_NUMBER in `ls -d "projects/$PROJECT_NAME"_* | sed s/[^[:digit:]]/\ /g`
    do
	if [ x$BUG_NUMBER != x4 ] ; then
	    echo "$PROJECT_NAME"_"$BUG_NUMBER".log: >> Makefile
	    echo -en "\t" >> Makefile
	    echo "./run.sh $PROJECT_NAME $BUG_NUMBER > \$@ 2> \$@.err" >> Makefile
	    echo >> Makefile
	fi
    done
done

echo clean: remove_exited_containers remove_images >> Makefile

for PROJECT_NAME in $PROJECTS
do
    for BUG_NUMBER in `ls -d "projects/$PROJECT_NAME"_* | sed s/[^[:digit:]]/\ /g`
    do
	if [ x$BUG_NUMBER != x4 ] ; then
	    echo -en "\t" >> Makefile
	    echo -n "rm -rf " >> Makefile
	    if [ x$PROJECT_NAME = xffmpeg -o x$PROJECT_NAME = xlibarchive ] ; then
		echo "projects/$PROJECT_NAME"_"$BUG_NUMBER/$PROJECT_NAME"_"$BUG_NUMBER"_codes " " >> Makefile
	    else
		echo "projects/$PROJECT_NAME"_"$BUG_NUMBER/$PROJECT_NAME"_"$BUG_NUMBER" " " >> Makefile
	    fi
            if [ x$PROJECT_NAME = xffmpeg ] ; then
		echo -en "\t" >> Makefile
		echo "rm -rf projects/$PROJECT_NAME"_"$BUG_NUMBER/x264_prev" >> Makefile
            fi
	    echo -en "\t" >> Makefile
	    echo "rm -f $PROJECT_NAME"_"$BUG_NUMBER".log "$PROJECT_NAME"_"$BUG_NUMBER".log.err >> Makefile	    
	fi
    done
done
echo >> Makefile

echo remove_exited_containers: >> Makefile
echo -en "\t" >> Makefile
echo "@EXITED_CONTAINERS=\`docker ps --all --filter \"status=exited\"| cut --bytes=1-12\` ; \\" >> Makefile
echo -en "\t" >> Makefile
echo "for CONTAINER_ID in \$\$EXITED_CONTAINERS ; do \\" >> Makefile
echo -en "\t\t" >> Makefile
echo "if [ x\$\$CONTAINER_ID != xCONTAINER -a x\$\$CONTAINER_ID != xID ] ; then \\" >> Makefile
echo -en "\t\t\t" >> Makefile
echo "docker rm \$\$CONTAINER_ID ; \\" >> Makefile
echo -en "\t\t" >> Makefile
echo "fi ; \\" >> Makefile
echo -en "\t" >> Makefile
echo "done" >> Makefile

echo >> Makefile

echo remove_images: >> Makefile
echo -en "\t" >> Makefile
echo "rm -f all_images.txt ; docker images > all_images.txt" >> Makefile
for PROJECT_NAME in $PROJECTS
do
    for BUG_NUMBER in `ls -d "projects/$PROJECT_NAME"_* | sed s/[^[:digit:]]/\ /g`
    do
	if [ x$BUG_NUMBER != x4 ] ; then
	    echo -en "\t" >> Makefile
	    echo "@grep $PROJECT_NAME"_"$BUG_NUMBER all_images.txt ; \\" >> Makefile
	    echo -en "\t" >> Makefile
	    echo "if [ \$\$? -eq 0 ] ; then \\" >> Makefile
	    echo -en "\t\t" >> Makefile
	    echo "docker rmi -f gcr.io/oss-fuzz/$PROJECT_NAME"_"$BUG_NUMBER ; \\" >> Makefile
	    echo -en "\t" >> Makefile
	    echo "fi" >> Makefile
	fi
    done
done
echo -en "\t" >> Makefile
echo "rm -rf all_images.txt" >> Makefile

echo >> Makefile

