#!/bin/bash
hashid=$1
: '
docker cp f1x/repair/Runtime.cpp $hashid:/src/f1x-oss-fuzz/f1x/repair/Runtime.cpp
docker cp f1x/repair/Runtime.h $hashid:/src/f1x-oss-fuzz/f1x/repair/Runtime.h
docker cp f1x/repair/SearchEngine.h $hashid:/src/f1x-oss-fuzz/f1x/repair/SearchEngine.h
docker cp f1x/repair/SearchEngine.cpp $hashid:/src/f1x-oss-fuzz/f1x/repair/SearchEngine.cpp
docker cp f1x/repair/Synthesis.cpp $hashid:/src/f1x-oss-fuzz/f1x/repair/Synthesis.cpp
'
docker cp scripts/afl-fuzz.c $hashid:/src/aflgo/afl-fuzz.c
docker cp scripts/config.h $hashid:/src/aflgo/config.h
docker cp executeAFLGO_address $hashid:/src/scripts/executeAFLGO_address
docker cp executeAFLGO $hashid:/src/scripts/executeAFLGO
