#!/bin/bash
usage="Usage: ./executeAFLGO.sh"

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
TIME_OUT=8h

INITIAL_LD_LIBRARY_PATH=$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/out:$LD_LIBRARY_PATH

f1x_cmd="f1x -f $BUGGY_FILE -t $TESTCASE -T 5000 -d $DRIVER -b ./project_build.sh -a -P /out -N ${BINARY} -o $SCRIPT_DIR/patches"
echo $f1x_cmd > $SCRIPT_DIR/f1xcmd.sh

rm -rf /out0
mkdir /out0
pushd $SCRIPT_DIR/../$SUBJECT/ >/dev/null
  echo "executing:"
  echo "ctimeout $TIME_OUT /src/aflgo/afl-fuzz -S ef709ce2 -z no -c 45m -i /in -o /out0 -m none -C -t 1000 -R $SCRIPT_DIR/f1xcmd.sh /out/${BINARY}_profile @@"
  timeout $TIME_OUT /src/aflgo/afl-fuzz -S ef709ce2 -z no -c 45m -i /in -o /out0  -m none -C -t 1000 -R $SCRIPT_DIR/f1xcmd.sh /out/${BINARY}_profile @@ | tee $SCRIPT_DIR/afl.txt
popd > /dev/null

rm -rf /out1
mkdir /out1
pushd $SCRIPT_DIR/../$SUBJECT/ >/dev/null
  echo "executing:"
  echo "ctimeout $TIME_OUT /src/aflgo/afl-fuzz -S ef709ce2 -z exp -c 45m -i /in -o /out1 -m none -C -t 1000 -R $SCRIPT_DIR/f1xcmd.sh /out/${BINARY}_profile @@"
  timeout $TIME_OUT /src/aflgo/afl-fuzz -S ef709ce2 -z exp -c 45m -i /in -o /out1 -m none -C -t 1000 -R $SCRIPT_DIR/f1xcmd.sh /out/${BINARY}_profile @@ | tee $SCRIPT_DIR/aflgo.txt
popd > /dev/null

rm -rf /out2
mkdir /out2
pushd $SCRIPT_DIR/../$SUBJECT/ >/dev/null
  echo "executing:"
  echo "ctimeout $TIME_OUT /src/aflgo/afl-fuzz -S ef709ce2 -z exp -c 45m -i /in -o /out2 -s pat -m none -C -t 1000 -R $SCRIPT_DIR/f1xcmd.sh /out/${BINARY}_profile @@"
  timeout $TIME_OUT /src/aflgo/afl-fuzz -S ef709ce2 -z exp -c 45m -i /in -o /out2 -s pat -m none -C -t 1000 -R $SCRIPT_DIR/f1xcmd.sh /out/${BINARY}_profile @@ | tee $SCRIPT_DIR/aflgo_pat.txt
popd > /dev/null

#rm -rf /out3
#mkdir /out3
#pushd $SCRIPT_DIR/../$SUBJECT/ >/dev/null
#  echo "executing:"
#  echo "ctimeout $TIME_OUT /src/aflgo/afl-fuzz -S ef709ce2 -z exp -c 45m -i /in -o /out3 -s par -C -t 1000 -R $SCRIPT_DIR/f1xcmd.sh /out/${BINARY}_profile @@"
  #timeout $TIME_OUT /src/aflgo/afl-fuzz -S ef709ce2 -z exp -c 45m -i /in -o /out3 -s par -C -t 1000 -R $SCRIPT_DIR/f1xcmd.sh /out/${BINARY}_profile @@ | tee $SCRIPT_DIR/aflgo_par.txt
#popd > /dev/null

rm -rf /out4
mkdir /out4
pushd $SCRIPT_DIR/../$SUBJECT/ >/dev/null
  echo "executing:"
  echo "ctimeout $TIME_OUT /src/aflgo/afl-fuzz -S ef709ce2 -z exp -c 45m -i /in -o /out4 -s part  -m none -C -t 1000 -R $SCRIPT_DIR/f1xcmd.sh /out/${BINARY}_profile @@"
  timeout $TIME_OUT /src/aflgo/afl-fuzz -S ef709ce2 -z exp -c 45m -i /in -o /out4 -s part -m none -C -t 1000 -R $SCRIPT_DIR/f1xcmd.sh /out/${BINARY}_profile @@ | tee $SCRIPT_DIR/aflgo_part.txt
popd > /dev/null

export LD_LIBRARY_PATH=$INITIAL_LD_LIBRARY_PATH
