#!/bin/bash
usage="Usage: ./executeAFLGO.sh"

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
TIME_OUT=24h

INITIAL_LD_LIBRARY_PATH=$LD_LIBRARY_PATH

cooling_time=120m
export LD_LIBRARY_PATH=/out:$LD_LIBRARY_PATH

prefix_f1x_cmd="f1x -f $BUGGY_FILE -t $TESTCASE -T 15000 -d $DRIVER -b ./project_build.sh -a -P /out -N ${BINARY} -M 16"

f1x_cmd="$prefix_f1x_cmd -o $SCRIPT_DIR/patches"
echo $f1x_cmd > $SCRIPT_DIR/f1xcmd.sh
rm -rf /out
mkdir /out
pushd $SCRIPT_DIR/../$SUBJECT/ >/dev/null
  echo "executing:"
  echo "timeout $TIME_OUT /src/aflgo/afl-fuzz -S ef709ce2 -z exp -c $cooling_time -i /in -o /out -s part ${MEMMODE} -C -t 1000 -R $SCRIPT_DIR/f1xcmd.sh /out/${BINARY}_profile @@"
  timeout $TIME_OUT /src/aflgo/afl-fuzz -S ef709ce2 -z exp -c $cooling_time -i /in -o /out -s part -C -t 1000 -R $SCRIPT_DIR/f1xcmd.sh /out/${BINARY}_profile @@
popd > /dev/null

export LD_LIBRARY_PATH=$INITIAL_LD_LIBRARY_PATH
